import React, { useMemo, useState } from "react";
import { Braces, CheckCircle2, Clipboard, Clock3, Code2, ExternalLink, Fingerprint, Landmark, RefreshCw, ShieldAlert } from "lucide-react";
import ToolPulse from "./ToolPulse";

const cleanNumber = (value) => value.toUpperCase().replace(/[^0-9T]/g, "");

export function isValidCorporateNumber(value) {
  const digits = cleanNumber(value).replace(/^T/, "");
  if (!/^\d{13}$/.test(digits)) return false;
  const base = digits.slice(1);
  let sum = 0;
  for (let i = 0; i < 12; i += 1) sum += Number(base[i]) * ((12 - i) % 2 === 0 ? 2 : 1);
  return Number(digits[0]) === 9 - (sum % 9);
}

const CopyButton = ({ value, lang }) => {
  const [done, setDone] = useState(false);
  return <button className="iconAction" disabled={!value} onClick={async () => { await navigator.clipboard.writeText(value); setDone(true); window.setTimeout(() => setDone(false), 1200); }}><Clipboard />{done ? (lang === "ja" ? "コピー済み" : "Copied") : (lang === "ja" ? "コピー" : "Copy")}</button>;
};

function JsonTool({ lang }) {
  const [input, setInput] = useState('{"name":"SunData","private":true}');
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");
  const run = (minify) => { try { setOutput(JSON.stringify(JSON.parse(input), null, minify ? 0 : 2)); setError(""); } catch (e) { setOutput(""); setError(e.message); } };
  return <article className="dailyCard dailyCardWide"><div className="dailyCardHead"><span className="dailyIcon mint"><Braces /></span><div><b>JSON</b><h3>{lang === "ja" ? "整形・検証" : "Format & validate"}</h3></div></div><div className="codeGrid"><label><span>{lang === "ja" ? "入力" : "Input"}</span><textarea value={input} onChange={(e) => setInput(e.target.value)} spellCheck="false" /></label><label><span>{lang === "ja" ? "結果" : "Result"}</span><textarea value={output} readOnly spellCheck="false" /></label></div>{error && <p className="inlineError" role="alert">{error}</p>}<div className="toolActions"><button onClick={() => run(false)}>{lang === "ja" ? "整形" : "Format"}</button><button className="ghostAction" onClick={() => run(true)}>{lang === "ja" ? "圧縮" : "Minify"}</button><CopyButton value={output} lang={lang} /></div><ToolPulse tool="JSON" lang={lang} /></article>;
}

function EncoderTool({ lang }) {
  const [mode, setMode] = useState("base64"); const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [error, setError] = useState("");
  const run = (decode) => { try { const result = mode === "base64" ? (decode ? new TextDecoder().decode(Uint8Array.from(atob(input.trim()), c => c.charCodeAt(0))) : btoa(String.fromCharCode(...new TextEncoder().encode(input)))) : (decode ? decodeURIComponent(input) : encodeURIComponent(input)); setOutput(result); setError(""); } catch { setOutput(""); setError(lang === "ja" ? "入力内容を確認してください。" : "Check the input and try again."); } };
  return <article className="dailyCard"><div className="dailyCardHead"><span className="dailyIcon blue"><Code2 /></span><div><b>ENCODER</b><h3>Base64 / URL</h3></div></div><div className="segmented"><button className={mode === "base64" ? "active" : ""} onClick={() => { setMode("base64"); setOutput(""); }}>Base64</button><button className={mode === "url" ? "active" : ""} onClick={() => { setMode("url"); setOutput(""); }}>URL</button></div><label className="stackField"><span>{lang === "ja" ? "テキスト" : "Text"}</span><textarea value={input} onChange={(e) => setInput(e.target.value)} /></label><label className="stackField"><span>{lang === "ja" ? "結果" : "Result"}</span><textarea value={output} readOnly /></label>{error && <p className="inlineError">{error}</p>}<div className="toolActions"><button onClick={() => run(false)}>{lang === "ja" ? "エンコード" : "Encode"}</button><button className="ghostAction" onClick={() => run(true)}>{lang === "ja" ? "デコード" : "Decode"}</button><CopyButton value={output} lang={lang} /></div><ToolPulse tool="Base64 / URL" lang={lang} /></article>;
}

function IdTimeTool({ lang }) {
  const [uuid, setUuid] = useState(() => crypto.randomUUID()); const [timestamp, setTimestamp] = useState(() => Math.floor(Date.now() / 1000));
  const date = useMemo(() => { const n = Number(timestamp); const d = new Date(String(timestamp).length > 10 ? n : n * 1000); return Number.isNaN(d.getTime()) ? null : d; }, [timestamp]);
  return <article className="dailyCard"><div className="dailyCardHead"><span className="dailyIcon coral"><Fingerprint /></span><div><b>GENERATORS</b><h3>{lang === "ja" ? "UUID・時刻変換" : "UUID & timestamp"}</h3></div></div><div className="miniTool"><span>UUID v4</span><code>{uuid}</code><div className="toolActions"><button onClick={() => setUuid(crypto.randomUUID())}><RefreshCw />{lang === "ja" ? "再生成" : "New"}</button><CopyButton value={uuid} lang={lang} /></div></div><div className="miniTool"><span>Unix timestamp</span><div className="timestampRow"><input inputMode="numeric" value={timestamp} onChange={(e) => setTimestamp(e.target.value.replace(/[^0-9]/g, ""))} /><button onClick={() => setTimestamp(Math.floor(Date.now() / 1000))}><Clock3 />NOW</button></div><output>{date ? `${date.toLocaleString(lang === "ja" ? "ja-JP" : "en-US")} · ${date.toISOString()}` : (lang === "ja" ? "有効な値を入力" : "Enter a valid value")}</output></div><ToolPulse tool={lang === "ja" ? "UUID・時刻変換" : "UUID & timestamp"} lang={lang} /></article>;
}

function NumberCheck({ lang }) {
  const [value, setValue] = useState(""); const normalized = cleanNumber(value); const digits = normalized.replace(/^T/, ""); const invoice = normalized.startsWith("T"); const lengthValid = /^\d{13}$/.test(digits); const checksum = lengthValid && isValidCorporateNumber(digits); const status = !value ? "idle" : !lengthValid ? "bad" : checksum ? "good" : invoice ? "neutral" : "bad";
  const messages = { idle: ["番号を入力すると形式を確認します。", "Enter a number to check its format."], bad: ["桁数またはチェックデジットが一致しません。", "Length or check digit does not match."], good: ["13桁とチェックデジットは有効です。", "The 13 digits and check digit are valid."], neutral: ["登録番号の形式は有効です。個人事業者番号は法人番号の計算対象外です。", "The registration-number format is valid. Sole-proprietor numbers do not use the corporate checksum."] };
  return <article className="dailyCard businessCard" id="number-check"><div className="dailyCardHead"><span className="dailyIcon gold"><Landmark /></span><div><b>JAPAN BUSINESS</b><h3>{lang === "ja" ? "法人・インボイス番号チェック" : "Corporate & invoice number check"}</h3></div></div><label className="stackField"><span>{lang === "ja" ? "法人番号（13桁）または登録番号（T＋13桁）" : "13-digit corporate number or T + 13 digits"}</span><input value={value} onChange={(e) => setValue(cleanNumber(e.target.value).slice(0, 14))} placeholder="T1234567890123" /></label><div className={`numberStatus ${status}`}>{status === "good" && <CheckCircle2 />}{status === "neutral" && <ShieldAlert />}{lang === "ja" ? messages[status][0] : messages[status][1]}</div><p className="toolNote">{lang === "ja" ? "形式確認だけでは実在や登録状態を証明できません。国税庁で最終確認してください。" : "Format alone does not prove existence or registration. Confirm with the NTA."}</p><div className="officialLinks"><a href="https://www.houjin-bangou.nta.go.jp/" target="_blank" rel="noreferrer">{lang === "ja" ? "法人番号公表サイト" : "Corporate registry"}<ExternalLink /></a><a href="https://www.invoice-kohyo.nta.go.jp/index.html" target="_blank" rel="noreferrer">{lang === "ja" ? "インボイス公表サイト" : "Invoice registry"}<ExternalLink /></a></div><ToolPulse tool={lang === "ja" ? "法人・インボイス番号チェック" : "Business number check"} lang={lang} /></article>;
}

const risks = [[3,"売上・入金と帳簿に差異がある","Sales, deposits and books do not reconcile"],[3,"個人支出と事業経費が混在している","Personal and business expenses are mixed"],[2,"領収書・請求書の不足や記載漏れがある","Receipts or invoices are missing/incomplete"],[3,"税金の期限管理に不安がある","Tax deadlines may be missed"],[2,"現金取引や役員貸付金が多い","Cash transactions or director loans are frequent"],[2,"外注費と給与の区分が曖昧である","Contractor fees and payroll may be misclassified"],[2,"取引先のインボイス登録を確認していない","Supplier invoice status is not checked"],[1,"電子取引データの保存ルールがない","Electronic records lack a retention rule"]];
function TaxCheck({ lang }) { const [checked,setChecked]=useState([]); const score=checked.reduce((s,i)=>s+risks[i][0],0); const level=score===0?"low":score<=4?"watch":"high"; const result={low:["注意項目は選択されていません。","No warning items selected."],watch:["確認推奨：証憑と帳簿を月次で照合しましょう。","Review recommended: reconcile records monthly."],high:["早めの整理推奨：税理士または税務署へ確認してください。","Act soon: review the details with a tax professional or tax office."]}[level]; return <article className="dailyCard dailyCardWide taxCard" id="tax-check"><div className="dailyCardHead"><span className="dailyIcon rose"><ShieldAlert /></span><div><b>SELF CHECK</b><h3>{lang === "ja" ? "税務リスク簡易チェック" : "Tax-risk self-check"}</h3></div></div><p className="toolNote emphasized">{lang === "ja" ? "整理用チェックです。税務判断、申告可否、調査可能性を判定するものではありません。" : "An organization checklist—not tax advice or an audit prediction."}</p><div className="riskChecklist">{risks.map((r,i)=><label key={r[1]}><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(c=>c.includes(i)?c.filter(x=>x!==i):[...c,i])}/><span>{lang === "ja"?r[1]:r[2]}</span></label>)}</div><div className={`riskResult ${level}`}><strong>{checked.length}<span> / {risks.length}</span></strong><p>{lang === "ja"?result[0]:result[1]}</p></div><a className="ntaLink" href="https://www.nta.go.jp/taxes/shiraberu/" target="_blank" rel="noreferrer">{lang === "ja" ? "国税庁「税について調べる」" : "NTA tax information"}<ExternalLink /></a><ToolPulse tool={lang === "ja" ? "税務リスク簡易チェック" : "Tax-risk self-check"} lang={lang} /></article>; }

export default function DailyTools({ lang }) { return <section className="dailyTools" id="daily-tools"><div className="sectionHead dailyHead"><span>DAILY WORKBENCH</span><h2>{lang === "ja" ? "IT・仕事の便利ツール" : "IT & work utilities"}</h2><p>{lang === "ja" ? "貼り付けて、確認して、すぐ使う。入力内容はブラウザ内だけで処理します。" : "Paste, check and use. Your input stays in this browser."}</p></div><div className="categoryLabel"><Code2 />{lang === "ja" ? "開発・データ" : "Developer & data"}</div><div className="dailyGrid"><JsonTool lang={lang}/><EncoderTool lang={lang}/><IdTimeTool lang={lang}/></div><div className="categoryLabel businessLabel"><Landmark />{lang === "ja" ? "日本の事業者向け" : "For businesses in Japan"}</div><div className="dailyGrid businessGrid"><NumberCheck lang={lang}/><TaxCheck lang={lang}/></div></section>; }
